Repository AY2021S2-CS2103T-W14-2/tp, pull requests merged in 2021-04, with the labels that each got.

#143 Add help command
  src/main/java/seedu/budgetbaby/logic/commands/HelpCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
Labels: priority.High, type.Story

#197 Fix invalid date bug
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/model/record/FinancialRecord.java
Labels: severity.High, type.Bug

#198 Fix bug relating to FinancialRecord model
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/model/record/Amount.java
  src/main/java/seedu/budgetbaby/model/record/Description.java
Labels: severity.Medium, type.Bug

#199 Fix documentation bugs regarding FR and Months
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/MainApp.java
  src/main/java/seedu/budgetbaby/commons/core/LogsCenter.java
  src/main/java/seedu/budgetbaby/commons/core/Messages.java
  src/main/java/seedu/budgetbaby/logic/commands/EditFrCommand.java
Labels: severity.VeryLow, type.Docs

#200 Draft Xinyue's Project Portfolio Page
  docs/team/eksinyue.md
Labels: type.Docs

#201 PE-D fixes for Category, find-fr and reset-filter
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/logic/commands/FindFrCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
  src/main/java/seedu/budgetbaby/logic/parser/ResetFilterCommandParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/record/Category.java
  src/test/java/seedu/budgetbaby/ablogic/parser/AddCommandParserTest.java
  src/test/java/seedu/budgetbaby/ablogic/parser/EditCommandParserTest.java
  src/test/java/seedu/budgetbaby/ablogic/parser/ParserUtilTest.java
  src/test/java/seedu/budgetbaby/abstorage/JsonAdaptedPersonTest.java
Labels: severity.High, type.Bug

#142 Unit tests for find and reset functions
  docs/UserGuide.md
  docs/images/features/category-stats.png
  docs/images/features/monthly-stats.png
  docs/images/features/redo.png
  docs/images/features/undo.png
  src/main/java/seedu/budgetbaby/commons/core/Messages.java
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/budgetbaby/model/Budget.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/model/month/UniqueMonthList.java
  src/main/java/seedu/budgetbaby/model/record/Category.java
  src/main/java/seedu/budgetbaby/storage/JsonAdaptedMonth.java
  src/test/java/seedu/budgetbaby/logic/commands/FindFrCommandTest.java
  src/test/java/seedu/budgetbaby/logic/commands/ResetFilterCommandTest.java
  src/test/java/seedu/budgetbaby/model/budget/BudgetTest.java
  src/test/java/seedu/budgetbaby/model/record/CategoryTest.java
  src/test/java/seedu/budgetbaby/testutil/TypicalBudgetTracker.java
Labels: priority.High, type.Task

#203 Add PE-D fixes for UI
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/resources/view/CategoryStatsWindow.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MonthStatsWindow.fxml
Labels: priority.High, severity.Medium, type.Bug

#204 Add PE-D fixes for UI and UG
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/storage/JsonAdaptedMonth.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Bug, type.Docs

#206 Unit tests
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/commons/core/Messages.java
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/test/java/seedu/budgetbaby/logic/commands/CommandTestUtil.java
  src/test/java/seedu/budgetbaby/logic/commands/DeleteFrCommandTest.java
  src/test/java/seedu/budgetbaby/logic/commands/EditFrCommandTest.java
  src/test/java/seedu/budgetbaby/logic/commands/SetBudgetCommandTest.java
  src/test/java/seedu/budgetbaby/testutil/TypicalIndexes.java
Labels: priority.High, type.Story

#207 Fix handling of invalid budget amount
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/ParserUtil.java
  src/main/java/seedu/budgetbaby/logic/parser/SetBudgetCommandParser.java
Labels: priority.High, type.Bug

#211 Modify categories shown on the side to show all categories
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogic.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/ui/BudgetDisplay.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/MonthStatsWindow.fxml
Labels: type.Enhancement

#216 Add unit tests for financial record and month related classes
  src/main/java/seedu/budgetbaby/commons/core/Messages.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecord.java
  src/main/java/seedu/budgetbaby/model/util/SampleDataUtil.java
  src/test/java/seedu/budgetbaby/logic/commands/AddFrCommandTest.java
  src/test/java/seedu/budgetbaby/logic/commands/CommandTestUtil.java
  src/test/java/seedu/budgetbaby/logic/commands/HelpCommandTest.java
  src/test/java/seedu/budgetbaby/logic/parser/AddFrCommandParserTest.java
  src/test/java/seedu/budgetbaby/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/budgetbaby/model/month/MonthTest.java
  src/test/java/seedu/budgetbaby/model/record/FinancialRecordListTest.java
  src/test/java/seedu/budgetbaby/model/record/FinancialRecordTest.java
  src/test/java/seedu/budgetbaby/testutil/BudgetTrackerBuilder.java
  src/test/java/seedu/budgetbaby/testutil/FinancialRecordBuilder.java
  src/test/java/seedu/budgetbaby/testutil/MonthBuilder.java
  src/test/java/seedu/budgetbaby/testutil/PersonBuilder.java
  src/test/java/seedu/budgetbaby/testutil/TypicalFinancialRecord.java
Labels: priority.Medium, type.Task

#220 Fix handling of setting a budget amount of zero
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/test/java/seedu/budgetbaby/logic/commands/SetBudgetCommandTest.java
Labels: priority.High, type.Bug

#221 Add tests of undo and redo
  src/test/java/seedu/budgetbaby/model/VersionedBudgetTrackerTest.java
  src/test/java/seedu/budgetbaby/testutil/BudgetTrackerBuilder.java
Labels: priority.High, type.Task

#224 Update UG with UI overview, command history and accelerators
  docs/UserGuide.md
  docs/images/Ui_Components.png
Labels: priority.High, type.Docs, type.Task

#225 Fix div tags appearing in UG
  docs/UserGuide.md
Labels: priority.High, type.Docs

#235 Update site personal documentation
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/team/yuheem.md
Labels: priority.High, type.Docs

#239 Update UI resolution
  src/main/java/seedu/budgetbaby/commons/core/GuiSettings.java
  src/main/java/seedu/budgetbaby/ui/BudgetDisplay.java
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#240 Add file encoding
  src/main/java/seedu/budgetbaby/commons/util/EncodeUtil.java
  src/main/java/seedu/budgetbaby/commons/util/FileUtil.java
  src/test/data/ConfigUtilTest/EmptyConfig.json
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/NotJsonFormatConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
Labels: priority.High, type.Enhancement, type.Task

#241 Remove unused test data files
  src/main/java/seedu/budgetbaby/logic/parser/CliSyntax.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonUserPrefsStorageTest/EmptyUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/NotJsonFormatUserPrefs.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
Labels: priority.High

#238 Fix bugs regarding financial record and month related features
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/MainApp.java
  src/main/java/seedu/budgetbaby/commons/core/Messages.java
  src/main/java/seedu/budgetbaby/logic/parser/ParserUtil.java
  src/main/java/seedu/budgetbaby/model/Budget.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/model/month/UniqueMonthList.java
  src/main/java/seedu/budgetbaby/model/month/exception/TotalExpenseOutOfBoundException.java
  src/main/java/seedu/budgetbaby/model/record/Amount.java
  src/main/java/seedu/budgetbaby/model/record/Description.java
  src/main/java/seedu/budgetbaby/model/util/SampleDataUtil.java
  src/test/java/seedu/budgetbaby/logic/commands/FindFrCommandTest.java
  src/test/java/seedu/budgetbaby/testutil/BudgetTrackerBuilder.java
  src/test/java/seedu/budgetbaby/testutil/TypicalBudgetTracker.java
  src/test/java/seedu/budgetbaby/testutil/TypicalFinancialRecord.java
Labels: severity.High, type.Bug

#251 Fixed issue where previous 6 months were not shown
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
Labels: priority.High, type.Bug

#254 Add statistics tests
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/test/java/seedu/budgetbaby/logic/statistics/CategoryStatisticsTest.java
  src/test/java/seedu/budgetbaby/logic/statistics/MonthStatisticsTest.java
  src/test/java/seedu/budgetbaby/logic/statistics/StatisticsTest.java
Labels: priority.High, priority.Medium

#252 Fix issue when loading encoded but corrupted data file
  src/main/java/seedu/budgetbaby/commons/util/EncodeUtil.java
  src/main/java/seedu/budgetbaby/commons/util/FileUtil.java
  src/main/java/seedu/budgetbaby/commons/util/JsonUtil.java
  src/main/java/seedu/budgetbaby/storage/JsonBudgetTrackerStorage.java
Labels: priority.High, type.Bug

#256 Update month and financial record related section in DG
  docs/DeveloperGuide.md
  docs/diagrams/AddFrActivityDiagram.puml
  docs/diagrams/ViewMonthActivityDiagram.puml
  docs/diagrams/ViewMonthSequenceDiagram.puml
  docs/images/AddFrActivityDiagram.png
  docs/images/ViewMonthActivityDiagram.png
  docs/images/ViewMonthSequenceDiagram.png
Labels: priority.High, type.Docs

#257 Update statistics bar colour and wrapped financial record description
  src/main/java/seedu/budgetbaby/ui/CategoryStatsWindow.java
  src/main/java/seedu/budgetbaby/ui/MonthStatsWindow.java
  src/main/resources/view/FinancialRecordListCard.fxml
Labels: priority.High, type.Task

#258 Update statistics windows title
  src/main/resources/view/CategoryStatsWindow.fxml
  src/main/resources/view/MonthStatsWindow.fxml
Labels: priority.High, type.Task

#259 Update MonthStatsWindow title to be more descriptive
  src/main/resources/view/MonthStatsWindow.fxml
Labels: priority.High, type.Task

#260 Update UG Screenshot
  docs/UserGuide.md
  docs/images/features/add-fr.png
  docs/images/features/category-stats.png
  docs/images/features/delete-fr.png
  docs/images/features/edit-fr.png
  docs/images/features/find-fr.png
  docs/images/features/monthly-stats.png
  docs/images/features/reset-filter.png
  docs/images/features/set-bg.png
  docs/images/features/view-month.png
  src/main/java/seedu/budgetbaby/logic/commands/FindFrCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/ResetFilterCommand.java
Labels: priority.High, type.Docs

#261 Update UG
  docs/UserGuide.md
Labels: priority.High, type.Docs

#262 Add undo and redo screenshots
  docs/UserGuide.md
  docs/images/features/redo.png
  docs/images/features/undo.png
Labels: priority.High, type.Docs

#264 Add undo/redo functionality to set-bg command
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
Labels: priority.High, type.Task

#266 Add implementation of Statistics features to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/CategoriesStatisticsSequenceDiagram.puml
  docs/diagrams/PastMonthsActivityDiagram.puml
  docs/diagrams/PastMonthsSequenceDiagram.puml
  docs/images/CategoriesStatisticsSequenceDiagram.png
  docs/images/PastMonthsActivityDiagram.png
  docs/images/PastMonthsSequenceDiagram.png
Labels: priority.High, type.Docs

#268 Add in details on statistics features in user guide
  docs/UserGuide.md
Labels: priority.High, type.Docs

#269 Update set budget section in DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SetBgActivityDiagram.puml
  docs/diagrams/SetBgSequenceDiagram.puml
  docs/images/SetBgActivityDiagram.png
  docs/images/SetBgSequenceDiagram.png
  docs/team/yuheem.md
Labels: priority.High, type.Docs

#274 Add note for statistics feature in UG and add picture
  docs/UserGuide.md
  docs/images/features/stats-side-panel.png
  docs/team/natosy.md
Labels: priority.Medium, type.Docs

#271 Update DG with undo/redo
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
Labels: priority.High, type.Docs

#276 Add undo/redo functionality to edit-fr command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/logic/commands/EditFrCommand.java
Labels: priority.High, type.Docs, type.Task

#279 Add TOC to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Docs
