Repository AY2021S2-CS2103T-W14-2/tp, pull requests merged in 2021-03, with the labels that each got.

#26 Add UI mockup
  README.md
  docs/images/Ui.png
  docs/index.md
Labels: type.docs

#28 Fix UI image path in index.md
  docs/index.md
Labels: bug, type.docs

#27 Rename profile picture
  docs/images/natosy.png
Labels: type.docs

#48 Update UI to display financial records
  src/main/java/seedu/budgetbaby/ui/FinancialRecordCard.java
  src/main/java/seedu/budgetbaby/ui/FinancialRecordListPanel.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/java/seedu/budgetbaby/ui/PersonListPanel.java
  src/main/resources/view/FinancialRecordListCard.fxml
  src/main/resources/view/FinancialRecordListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#50 Update overall UI
  copyright.txt
  src/main/java/seedu/budgetbaby/commons/core/GuiSettings.java
  src/main/java/seedu/budgetbaby/ui/HelpWindow.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/java/seedu/budgetbaby/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/budgetbaby_32.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/budgetbaby/abmodel/ModelManagerTest.java
  src/test/java/seedu/budgetbaby/abstorage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/budgetbaby/abstorage/StorageManagerTest.java
  src/test/java/seedu/budgetbaby/commons/util/AppUtilTest.java
Labels: priority.High, type.Task

#54 Create Statistic models
  src/main/java/seedu/budgetbaby/model/statistics/CategoryStatistic.java
  src/main/java/seedu/budgetbaby/model/statistics/DayStatistic.java
  src/main/java/seedu/budgetbaby/model/statistics/MonthStatistic.java
  src/main/java/seedu/budgetbaby/model/statistics/Statistic.java
  src/main/java/seedu/budgetbaby/model/statistics/WeekStatistic.java
Labels: priority.High

#57 Add set monthly budget feature
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
  src/main/java/seedu/budgetbaby/logic/parser/ParserUtil.java
  src/main/java/seedu/budgetbaby/logic/parser/SetBudgetCommandParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/budget/Budget.java
  src/test/java/seedu/budgetbaby/model/budget/BudgetTest.java
Labels: priority.High, type.Story

#58 Add & integrate month model
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogic.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/TimestampParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/ReadOnlyBudgetTracker.java
  src/main/java/seedu/budgetbaby/model/budget/Budget.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/model/month/UniqueMonthList.java
  src/main/java/seedu/budgetbaby/model/month/exception/DuplicateMonthException.java
  src/main/java/seedu/budgetbaby/model/month/exception/MonthMismatchException.java
  src/main/java/seedu/budgetbaby/model/month/exception/MonthNotFoundException.java
  src/main/java/seedu/budgetbaby/model/record/Amount.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecord.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecordList.java
  src/main/java/seedu/budgetbaby/model/record/exception/FinancialRecordNotFoundException.java
  src/main/java/seedu/budgetbaby/model/util/SampleDataUtil.java
  src/main/java/seedu/budgetbaby/storage/JsonAdaptedMonth.java
  src/main/java/seedu/budgetbaby/storage/JsonSerializableBudgetTracker.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/test/java/seedu/budgetbaby/model/budget/BudgetTest.java
Labels: priority.High, type.Task

#64 Update budget model to handle a default value
  src/main/java/seedu/budgetbaby/model/budget/Budget.java
  src/main/java/seedu/budgetbaby/model/month/UniqueMonthList.java
Labels: priority.High, type.Task

#68 Add methods for calculating remaining budget
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/model/record/Amount.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecordList.java
Labels: type.Task

#66 Update UI to display budget panel, timestamp and categories in financial records
  src/main/java/seedu/budgetbaby/commons/core/GuiSettings.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/model/record/Category.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecord.java
  src/main/java/seedu/budgetbaby/storage/JsonAdaptedFinancialRecord.java
  src/main/java/seedu/budgetbaby/ui/BudgetDisplay.java
  src/main/java/seedu/budgetbaby/ui/FinancialRecordCard.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/FinancialRecordListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#77 Update user and developer guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low, severity.Low

#87 Implement method to obtain past 6 months of budget and spending information
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogic.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/logic/statistics/CategoryStatistic.java
  src/main/java/seedu/budgetbaby/logic/statistics/DayStatistic.java
  src/main/java/seedu/budgetbaby/logic/statistics/MonthStatistic.java
  src/main/java/seedu/budgetbaby/logic/statistics/MonthStatistics.java
  src/main/java/seedu/budgetbaby/logic/statistics/Statistic.java
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/logic/statistics/WeekStatistic.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
Labels: priority.High, type.Story

#91 Add design of Logic component to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddFinancialRecordSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/AddFinancialRecordSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: priority.High, type.Docs

#96 Update and add Architecture details to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddFrSequenceDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: priority.High, type.Docs

#95 Update DG UI Model Component
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Docs

#97 Category filter command to filter financial records by category
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/budgetbaby/logic/commands/CategoryFilterCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/ResetFilterCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
  src/main/java/seedu/budgetbaby/logic/parser/CategoryFilterCommandParser.java
  src/main/java/seedu/budgetbaby/logic/parser/ResetFilterCommandParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/month/UniqueMonthList.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecordList.java
  src/test/java/seedu/budgetbaby/logic/commands/ResetFilterCommandTest.java
Labels: priority.High, type.Task

#100 Resolve duplicate sections for design in DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Bug, type.Docs

#98 Add event listener to update budget panel
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogic.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/ui/BudgetDisplay.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/java/seedu/budgetbaby/ui/UiManager.java
  src/main/resources/images/budgetbaby.png
  src/main/resources/images/budgetbaby_32.png
  src/main/resources/view/BudgetDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/budgetbaby/commons/util/AppUtilTest.java
Labels: priority.High, type.Task

#104 Implement method for viewing top 5 categories spent for every month
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogic.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/logic/statistics/CategoryStatistics.java
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
Labels: priority.High, type.Story

#106 Update UI to show top categories
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/ui/BudgetDisplay.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/resources/view/BudgetDisplay.fxml
Labels: priority.High, type.Story

#111 Fix set-bg command execution to refresh UI immediately
  src/main/java/seedu/budgetbaby/logic/commands/CommandResult.java
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
Labels: priority.High, type.Bug

#118 Update UG table of contents, purpose and target audience
  docs/UserGuide.md
Labels: priority.High, type.Docs

#119 Update User Guide Features section
  docs/UserGuide.md
Labels: priority.High, type.Docs

#117 Update Quick Start of UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  docs/index.md
Labels: priority.High, type.Docs

#121 Fix anchor issues in UG table of contents
  docs/UserGuide.md
Labels: priority.High, type.Docs

#122 Fix anchor issues in UG TOC
  docs/UserGuide.md
Labels: severity.High, type.Docs

#123 Fix UG typos and update features with screenshots
  docs/UserGuide.md
  docs/images/features/add-fr.png
  docs/images/features/delete-fr.png
  docs/images/features/find-fr.png
  docs/images/features/reset-filter.png
  docs/images/features/set-bg.png
Labels: priority.High, type.Story

#124 Improve language, style and tone of UG
  docs/UserGuide.md
  docs/images/features/view-month.png
Labels: priority.High, type.Docs

#108 Implement and document find and reset command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ResetActivityDiagram.puml
  docs/diagrams/ResetSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ResetActivityDiagram.png
  docs/images/ResetSequenceDiagram.png
  docs/images/johndoe.png
  src/main/java/seedu/budgetbaby/logic/commands/CategoryFilterCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/FindFrCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
  src/main/java/seedu/budgetbaby/logic/parser/CategoryFilterCommandParser.java
  src/main/java/seedu/budgetbaby/logic/parser/FindFrCommandParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
Labels: priority.High, type.Story

#128 Implement exit command
  src/main/java/seedu/budgetbaby/logic/commands/ExitCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
Labels: priority.High, type.Story

#129 v1.3b user guide improvement
  docs/UserGuide.md
Labels: priority.High, type.Docs

#131 Add edit-fr command and add timestamp argument to add-fr command
  src/main/java/seedu/budgetbaby/logic/commands/AddFrCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/EditFrCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/AddFrCommandParser.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
  src/main/java/seedu/budgetbaby/logic/parser/CliSyntax.java
  src/main/java/seedu/budgetbaby/logic/parser/EditFrCommandParser.java
  src/main/java/seedu/budgetbaby/logic/parser/ParserUtil.java
  src/main/java/seedu/budgetbaby/logic/parser/YearMonthParser.java
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/model/month/UniqueMonthList.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecord.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecordList.java
  src/main/java/seedu/budgetbaby/storage/JsonAdaptedFinancialRecord.java
  src/main/java/seedu/budgetbaby/ui/FinancialRecordCard.java
Labels: priority.High, type.Enhancement, type.Story

#134 Enable users to edit a financial record's timestamp
  src/main/java/seedu/budgetbaby/Main.java
  src/main/java/seedu/budgetbaby/logic/commands/EditFrCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/EditFrCommandParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
Labels: priority.High, type.Enhancement

#136 Add undo/redo command
  src/main/java/seedu/budgetbaby/ablogic/commands/ExitCommand.java
  src/main/java/seedu/budgetbaby/ablogic/commands/HelpCommand.java
  src/main/java/seedu/budgetbaby/commons/util/InvalidationListenerManager.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/logic/commands/AddFrCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/CommandResult.java
  src/main/java/seedu/budgetbaby/logic/commands/DeleteFrCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/EditFrCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/ExitCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/RedoCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/SetBudgetCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/UndoCommand.java
  src/main/java/seedu/budgetbaby/logic/commands/ViewMonthCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/BudgetBabyParser.java
  src/main/java/seedu/budgetbaby/logic/parser/RedoCommandParser.java
  src/main/java/seedu/budgetbaby/logic/parser/UndoCommandParser.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/BudgetTracker.java
  src/main/java/seedu/budgetbaby/model/ReadOnlyBudgetTracker.java
  src/main/java/seedu/budgetbaby/model/VersionedBudgetTracker.java
  src/main/java/seedu/budgetbaby/model/record/FinancialRecordList.java
  src/main/java/seedu/budgetbaby/ui/BudgetDisplay.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/resources/view/BudgetDisplay.fxml
  src/test/java/seedu/budgetbaby/ablogic/commands/CommandResultTest.java
  src/test/java/seedu/budgetbaby/ablogic/commands/ExitCommandTest.java
  src/test/java/seedu/budgetbaby/ablogic/commands/HelpCommandTest.java
Labels: priority.High, type.Enhancement, type.Story

#144 Add multiple deletion of financial records
  src/main/java/seedu/budgetbaby/commons/core/index/Index.java
  src/main/java/seedu/budgetbaby/logic/commands/DeleteFrCommand.java
  src/main/java/seedu/budgetbaby/logic/parser/DeleteFrCommandParser.java
Labels: priority.High, type.Enhancement

#148 Add category statistics UI
  src/main/java/seedu/budgetbaby/ui/CategoryStatsWindow.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/java/seedu/budgetbaby/ui/UiManager.java
  src/main/resources/view/CategoryStatsWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Enhancement, type.Task

#133 Add edit-fr command to user guide & miscellaneous changes
  docs/UserGuide.md
  docs/images/features/add-fr.png
  docs/images/features/edit-fr.png
  src/main/java/seedu/budgetbaby/logic/commands/AddFrCommand.java
Labels: type.Docs

#150 Implement month statistics UI window
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogic.java
  src/main/java/seedu/budgetbaby/logic/BudgetBabyLogicManager.java
  src/main/java/seedu/budgetbaby/logic/statistics/MonthStatistics.java
  src/main/java/seedu/budgetbaby/logic/statistics/Statistics.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModel.java
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
  src/main/java/seedu/budgetbaby/model/month/Month.java
  src/main/java/seedu/budgetbaby/ui/MainWindow.java
  src/main/java/seedu/budgetbaby/ui/MonthStatsWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MonthStatsWindow.fxml
Labels: priority.High, type.Story

#139 Fix IndexOutOfBound Exception after deleting FR
  src/main/java/seedu/budgetbaby/model/BudgetBabyModelManager.java
Labels: severity.Medium, type.Bug

#145 Add command history
  src/main/java/seedu/budgetbaby/ui/CommandBox.java
Labels: priority.Medium
